development:
  database: school_development
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: postgres 
  password: 32TfQA 
  host: localhost
  pool: 5
  port: 5432
  min_messages: WARNING

test:
  database: school_test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: postgres
  password: 32TfQA
  host: localhost
  pool: 5
  port: 5432
  min_messages: WARNING

production:
  database: school_production
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: postgres
  password: 32TfQA
  host: localhost
  pool: 5
  port: 5432
  min_messages: WARNING
